同步函数，oop
php/doc-zh pull request #115
Opened 2021-11-21 15:07 UTC by mowangjuanzi

2021-11-21 19:11 UTC, shiny commented
a lot of work! 
thank you for the contribution to the community.

2021-11-21 19:25 UTC, shiny requested changes
先看了一个文件，时间太晚了，剩下的慢慢 review，有谁有空也可以帮忙一起看下。

2021-11-21 19:25 UTC, shiny commented on language/oop5/traits.xml
>   <sect1 xml:id="language.oop5.traits" xmlns="http://docbook.org/ns/docbook">
第一句 “As of PHP 5.4.0,”  已经移除

2021-11-21 19:25 UTC, shiny commented on language/oop5/traits.xml
> +    支持公有、受保护和私有方法。PHP 8.0.0 之前，
此处 public、protected、private 不译反而更易理解

2021-11-21 20:33 UTC, shiny requested changes
过了一遍

2021-11-21 20:33 UTC, shiny commented on language/oop5/inheritance.xml
> +   子类无法访问父类的私有方法。因此，子类会不考虑正常的继承规则而重新实现私有方法。
“may” 
因此，子类**无需**考虑正常的继承规则而重新实现私有方法。

2021-11-21 20:33 UTC, shiny commented on language/oop5/inheritance.xml
> +   然而，从 PHP 8.0.0 起， <literal>final</literal> 和 <literal>static</literal>
"Prior to" 是 "PHP 8.0.0" 之前

2021-11-21 20:33 UTC, shiny commented on language/oop5/magic.xml
> +     <classname>Serializable</classname> 接口替代。
Use <link linkend="object.serialize">__serialize()</link> instead.

2021-11-21 20:33 UTC, shiny commented on language/oop5/magic.xml
> +     在 PHP 7.4。0 之前，返回值 <emphasis>必须</emphasis> 是 <type>string</type>
7.4.0

2021-11-21 20:33 UTC, shiny commented on language/oop5/magic.xml
- 推荐使用中文标点：顿号（、）而不是逗号（，）
- 并移除英文表达方式：and

2021-11-21 20:33 UTC, shiny commented on language/oop5/changelog.xml
> +       进行参数解包。该行为不是故意的，因此被删除。
> 该行为不是故意的，因此被删除。

该功能不是有意设计的，因此被删除。

2021-11-21 20:33 UTC, shiny commented on language/oop5/changelog.xml
> +       组声明：同一个命名空间导入的类，函数和常量现在可以组合在一个 use 语句中。
同样，推荐用中文顿号标点，并注意不要把英文惯用的 a, b and c 直译成 a，b 和 c。
而应该考虑中文表达方式。

2021-11-21 20:34 UTC, shiny commented
and you can click "Resolve conversation" button once problem solved.

2021-11-22 14:34 UTC, mowangjuanzi commented
@shiny 我还有一个问题哇。比如说 `language-snippets.ent` 文件，它现在已经翻译到了 `eacabc8e152598143b08aa8ad83270c5caece6a6`。最新commit 是 `dfa86bcd6d25c244c5c18d8da25878dd71e299df`。
中间更新了很多的 commit。 但是我只想翻译到其中的一部分。比如说 2021年8月的某个 commit 。不知道这种是否可行呢？还是说必须得更新到最新 commit 才合适？

2021-11-22 14:35 UTC, mowangjuanzi commented
@shiny 我还有一个问题哇。比如说 `language-snippets.ent` 
文件，它现在已经翻译到了 
`eacabc8e152598143b08aa8ad83270c5caece6a6`。最新commit 是 
`dfa86bcd6d25c244c5c18d8da25878dd71e299df`。
中间更新了很多的 commit。 但是我只想翻译到其中的一部分。比如说 
2021年8月的某个 commit 。不知道这种是否可行呢？还是说必须得更新到最新 commit 
才合适？

2021-11-22 17:08 UTC, shiny commented
1. 不能出现编译错误是大前提
2. 方便所有人核对是小前提（降低维护成本）

目前来看，从 `eacabc8e152598143b08aa8ad83270c5caece6a6` 到八月的某个 commit（比如 `235297daeda99773f68ee59e2efff048e98c1dc5`），中间所有的变化都提交上来，还是比较方便的。
`git diff eacabc8e152598143b08aa8ad83270c5caece6a6 235297daeda99773f68ee59e2efff048e98c1dc5 language-snippets.ent` 可以追踪到两个 commit 之间的所有变化。

如果你的意思是只翻译一个 commit 里变更的部分，会有这样的问题：无法跟踪中间几个 commit 的变化；下次如果要更新，只能花费大量时间去核对每一句内容。

所以我过去的实践是，如果没有时间，要么放弃，要么干脆直接把英文更新过来，然后只翻译部分内容。有时候读者看到英文内容也会来参与翻译。

2021-11-22 18:21 UTC, merged