translate
php/doc-zh pull request #123
Opened 2021-11-27 13:36 UTC by mowangjuanzi

enum 基础那个文件commit 写错了。提交历史中我没看到该commit id

2021-11-28 01:48 UTC, sy-records commented
enum那个文件？

2021-11-28 01:54 UTC, mowangjuanzi commented
是的。你可以看看这个链接：https://github.com/php/doc-en/commits/master/language/types/enumerations.xml

2021-11-28 02:00 UTC, sy-records commented
那这个可能就是复制错了，可以对比下内容改正commit id

2021-11-28 02:02 UTC, mowangjuanzi commented
> 那这个可能就是复制错了，可以对比下内容改正commit id

该文件就更新了一次🤔

2021-11-28 02:07 UTC, sy-records commented
嗯。。看你已经改了

2021-11-29 14:16 UTC, shiny requested changes
全部 Review 了下

2021-11-29 14:16 UTC, shiny commented on language/predefined/exception.xml
>   xmlns="http://docbook.org/ns/docbook"
此外，如果原来的文件不带版本号，添加版本号时，需要一一核对内容和对应的版本是否一致。
这个文件和标注的 `cdaea0421544885f02ff3d36bd203dc01b78299e ` 是有差异的，少了一段 `<ooclass>`

2021-11-29 14:16 UTC, shiny commented on language/predefined/iterator/valid.xml
>   <refsect1 role="description">
`en-revision` 可以更新到 `35b57d9df064ca7e1496fb73c4b9c1e30a7cd611`

2021-11-29 16:17 UTC, mowangjuanzi commented on language/predefined/exception.xml
>   xmlns="http://docbook.org/ns/docbook"
我以后一定注意这个问题

2021-11-29 16:18 UTC, mowangjuanzi commented
辛苦了

2021-11-30 19:20 UTC, merged

2021-11-30 19:21 UTC, shiny commented
👏
Done