Update stream related documentation to the latest version
php/doc-zh pull request #147
Opened 2021-12-17 02:48 UTC by her-cat

2021-12-17 10:37 UTC, shiny requested changes
感谢贡献，主要的问题是版本差异没有完整更新。
写了一篇文章，介绍了下如何用 IDEA 追踪差异，供参考

https://lapis-fact-ecb.notion.site/083310e34f744f429424be9762edaa21

2021-12-17 10:39 UTC, her-cat commented
好的，我再整理一下

发自我的iPhone


------------------ Original ------------------
From: DAI JIE ***@***.***&gt;
Date: Fri,Dec 17,2021 6:38 PM
To: php/doc-zh ***@***.***&gt;
Cc: 她和她的猫 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [php/doc-zh] Update stream related documentation to the latestversion (PR #147)

2021-12-21 08:32 UTC, her-cat commented on reference/stream/functions/stream-set-blocking.xml
> -<!-- EN-Revision: b5e5847fa94bc1bdc4eae3ca444c59272babfed1 Maintainer: Avenger Status: ready -->
前一位翻译者同步英文文档的翻译时，没有更新版本号。
https://github.com/php/doc-zh/commit/64685d7ffd79a5c255bfa2a94f5f1b16de78819b

2021-12-21 08:39 UTC, her-cat commented
@shiny 上面提到的几个问题已经处理了。

2021-12-22 15:14 UTC, shiny requested changes

2021-12-22 15:14 UTC, shiny commented on reference/stream/functions/stream-wrapper-register.xml
> +       STREAM_IS_URL。默认为 0，本地流。
<constant> 标记丢了，根据 diff 的结果， 这个标记尚未在英文版中移除。

2021-12-22 15:15 UTC, shiny commented on reference/stream/functions/stream-wrapper-register.xml
> +       STREAM_IS_URL。默认为 0，本地流。
就剩这个问题了

2021-12-23 09:09 UTC, her-cat commented
@shiny 抱歉，没注意到😂，已经改好了。

2021-12-29 18:46 UTC, merged