新增 APCUIterator 翻译
php/doc-zh pull request #157
Opened 2021-12-19 02:58 UTC by haytoo

2021-12-19 03:23 UTC, sy-records requested changes

2021-12-19 03:23 UTC, sy-records commented on reference/apcu/apcuiterator.xml
> + <title>The APCUIterator 类</title>
```suggestion
 <title>APCUIterator 类</title>
```

2021-12-19 03:44 UTC, sy-records commented on reference/apcu/apcuiterator.xml
> +    此外，使用正则表达式匹配是更高效的，因为它已经被移到了 C 级（C level）。
这里可能还需要再优化下语句

2021-12-19 19:12 UTC, shiny commented on reference/apcu/apcuiterator.xml
> +    此外，使用正则表达式匹配是更高效的，因为它已经被移到了 C 级（C level）。
这里的 

> Also, using regular expression
    matching is more efficient as it's been moved to the C level.

是指 C 语言层级吧？ “C 级” 的翻译有点困惑。

2021-12-20 01:16 UTC, haytoo commented on reference/apcu/apcuiterator.xml
> +    此外，使用正则表达式匹配是更高效的，因为它已经被移到了 C 级（C level）。
对的，是 C 语言层级，我改改。

2021-12-22 15:18 UTC, merged