Update socket related document
php/doc-zh pull request #162
Opened 2021-12-24 08:34 UTC by her-cat

2021-12-24 19:39 UTC, shiny requested changes

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     Mac OS X 和 FreeBSD，不包括 Linux 和 Windows。
请阅读原文核对下

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
missing "PHP"

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
同上

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
同上

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
同上

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
同上

2021-12-24 19:39 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
同上

2021-12-24 19:42 UTC, shiny commented on reference/sockets/constants.xml
> +     从 8.1.0 开始可用。
一般指代 PHP 的版本号时，绝大多数场景下原文都是带 “PHP” 三个字的。
经常会有其他 library 的版本号。若不着重强调 PHP 三个字，易混淆。

2021-12-24 19:43 UTC, shiny commented on reference/sockets/constants.xml
> +     Mac OS X 和 FreeBSD，不包括 Linux 和 Windows。
Mac OS X 是以前的叫法，现在改成了 macOS。
手册中涉及到的词均已调整。这一句的原文也改了。

2021-12-25 03:33 UTC, her-cat commented
@shiny 已改正。

2021-12-25 09:33 UTC, merged