翻译新增文件incompatible.xml
php/doc-zh pull request #189
Opened 2022-01-25 15:06 UTC by zhonglang1906

翻译新增文件php81版本 incompatible.xml

2022-01-25 15:33 UTC, mowangjuanzi commented on appendices/migration81/incompatible.xml
> +  <title>Standard PHP Library (SPL)</title>
这里可以使用 https://www.php.net/manual/zh/book.spl.php 的翻译：`PHP 标准库`

2022-01-25 15:53 UTC, mowangjuanzi commented on appendices/migration81/incompatible.xml
> +   使用 <function>is_resource</function> 的返回值检查应该被替换成 &false;。
这里的意思是返回值检查应该从 is_resource 检查是否是一个资源更改为检查返回值是否等于 false

2022-01-25 15:59 UTC, mowangjuanzi commented on appendices/migration81/incompatible.xml
> +   默认错误处理模式已经由 "silent" 变成了 "exceptions"，更多详情及如何设置该属性请参见 <link linkend="mysqli-driver.report-mode">MySQLi reporting mode</link> 。
建议注意下标点符号，需要把英文标点符号替换为中文

2022-01-26 00:11 UTC, sy-records requested changes
感谢参与翻译，需要注意一下翻译中的标点符号以及中英文的间隔等。可以先看一下 README 中的注意事项。

2022-01-26 00:11 UTC, sy-records commented on appendices/migration81/incompatible.xml
> + <title>不向后兼容的变更 </title>
```suggestion
 <title>不向后兼容的变更</title>
```

2022-01-26 00:11 UTC, sy-records commented on appendices/migration81/incompatible.xml
> +   现在 <function>mysqli_fetch_fields</function>, 和
```suggestion
   现在 <function>mysqli_fetch_fields</function>，和
```

2022-01-26 00:11 UTC, sy-records commented on appendices/migration81/incompatible.xml
> +   <function>openssl_cms_encrypt</function> 将默认使用 AES-128-CBC， 而非 RC2-40。
```suggestion
   <function>openssl_cms_encrypt</function> 将默认使用 AES-128-CBC，而非 RC2-40。
```

2022-01-26 00:11 UTC, sy-records commented on appendices/migration81/incompatible.xml
> +   为了遵守 <interfacename>ArrayAccess</interfacename> 接口,
```suggestion
   为了遵守 <interfacename>ArrayAccess</interfacename> 接口，
```

标点使用中文符号

2022-01-26 00:11 UTC, sy-records commented on appendices/migration81/incompatible.xml
> +   这更准确地模拟了自PHP7.0以来的引用注解。
```suggestion
   这更准确地模拟了自 PHP7.0 以来的引用注解。
```

2022-01-26 05:13 UTC, zhonglang1906 commented
好的，感谢review

2022-01-26 05:15 UTC, zhonglang1906 commented on appendices/migration81/incompatible.xml
> +   默认错误处理模式已经由 "silent" 变成了 "exceptions"，更多详情及如何设置该属性请参见 <link linkend="mysqli-driver.report-mode">MySQLi reporting mode</link> 。
😀我再改一下

2022-01-26 05:24 UTC, zhonglang1906 commented on appendices/migration81/incompatible.xml
> +   使用 <function>is_resource</function> 的返回值检查应该被替换成 &false;。
好的，感谢review

2022-01-26 05:39 UTC, zhonglang1906 commented on appendices/migration81/incompatible.xml
> +   这更准确地模拟了自PHP7.0以来的引用注解。
好的，感谢review，我再改改

2022-01-26 05:53 UTC, closed without merging