Calendar 翻译
php/doc-zh pull request #195
Opened 2022-02-09 11:18 UTC by mowangjuanzi

这里提及了四种日历。分别是：

- [儒略历](https://zh.wikipedia.org/wiki/%E5%84%92%E7%95%A5%E6%9B%86) 和 [儒略日](https://zh.wikipedia.org/wiki/%E5%84%92%E7%95%A5%E6%97%A5) 儒略日数, 儒略日期,儒略日 都有对应翻译
- [格里历](https://zh.wikipedia.org/wiki/%E6%A0%BC%E9%87%8C%E6%9B%86) 这个就是国内说的阳历，但是因为为了区分阳历(也有可能指的是中国古代的夏历)的另外一个意思。所以我都将其翻译成公历。
- [希伯来历](https://zh.wikipedia.org/wiki/%E5%B8%8C%E4%BC%AF%E4%BE%86%E6%9B%86) 直译的英文，翻译的是"犹太历"
- [法国历](https://zh.wikipedia.org/wiki/%E6%B3%95%E5%9C%8B%E5%85%B1%E5%92%8C%E6%9B%86) 直译为"法国共和历"，但是文中也写到，中文一般称为”法国历“

这些都挺烧脑的。如果还有疑问，可以继续沟通。

2022-02-13 05:54 UTC, jhdxr commented
我认为`日历`和`历法`两个词在中文中是不同的。引用一下wiki上的定义
> 历法是用年、月、日等时间单位计算时间的方法。
> 日历是一种日常使用的出版物，用于记载时间。 

新华字典对日历这一条的（相关）解释
>  2.今指记有年﹑月﹑日﹑星期﹑节气﹑纪念日等的本子﹐一年一本﹐每日一页﹐逐日揭去。有挂在墙上的﹐也有摆在桌上的。

换言之，历法指的是一种方法，公历、农历、希伯来历等等这些都是定义了如何去计算时间，所以是历法。

我对于将calendar这个扩展翻译为日历扩展没啥异议，因为其中不少函数也都是计算日期/星期的，符合我们日常生活中对日历一词的使用。但具体到这个PR中的内容，我看了一下我认为依然翻译成历法更为妥当。例如 _日历扩展提供了一系列用于简化不同**日历**间格式转换的函数_ ，如果看了下后续的说明，这个说的是在不同历法间进行转换，类似的情况我倾向于保留原本的翻译。


BTW，这个PR里包含了很多与calendar无关的格式化的内容（加个空格啥的），总体上来说我也支持这样子的修改，但是建议放在单独的PR或者直接提交，不建议与有需要review或讨论的PR混在一起，增加了review的成本_(:з」∠)

2022-02-15 03:56 UTC, mowangjuanzi commented
@jhdxr 现在不是对 Calendar 的翻译有歧义嘛，那我把文档中没有日历的再抽出来，然后新提交一个PR。这样可能会减少一些 review 的成本。你觉得咋样？

2022-02-15 04:26 UTC, jhdxr commented
> @jhdxr 现在不是对 Calendar 的翻译有歧义嘛，那我把文档中没有“日历”这两个字的再抽出来，然后新提交一个PR。这样可能会减少一些 review 的成本。你觉得咋样？

好的

2022-09-01 09:24 UTC, mowangjuanzi commented
现在在看。感觉适合翻译成 `历法`。我都想把这里的所有 `日历` 替换成 `历法` 了。

2022-12-26 09:10 UTC, jhdxr requested changes

2022-12-26 09:10 UTC, jhdxr commented on reference/calendar/functions/jddayofweek.xml
> +           返回 string 类型的星期几（英文 —— 公历）
这个我觉得可以写成`以英文返回公历形式的 string 类型的星期几`，或者如果要更贴近原文的话，括号里翻成`公历形式的英文`或`英文公历`？我对于英文之所以加连字符的理解是这样子就是个形容词了，但中文还保留这半个破折号感觉没啥必要。。。

2022-12-26 09:10 UTC, jhdxr commented on reference/calendar/functions/jddayofweek.xml
> +           返回 string 类型的星期几缩写（英文 —— 公历）
同上

2022-12-26 09:10 UTC, jhdxr commented on reference/calendar/functions/cal-from-jd.xml
> +    ）、星期和月份的缩写和全写、日期的 string 形式是“月/日/年”。
与`缩写`相对的，一般来说称之为`全称`？我理解`全写`这个说法是之前的翻译就已经使用了的，但我谷歌了一下这个词语并没有找到任何这么使用的地方。

2022-12-26 09:33 UTC, mowangjuanzi commented on reference/calendar/functions/cal-from-jd.xml
> +    ）、星期和月份的缩写和全写、日期的 string 形式是“月/日/年”。
我也忘记当时为了写“全写”了。而且现在来看，也是觉得“全写”怪怪的，不让“全称”好。

2022-12-26 18:09 UTC, jhdxr approved these changes
LGTM

2022-12-27 00:20 UTC, sy-records approved these changes

2022-12-27 00:20 UTC, merged