更新 Calendar 翻译后没有带日历/历法的文档
php/doc-zh pull request #203
Opened 2022-02-15 04:15 UTC by mowangjuanzi

https://github.com/php/doc-zh/pull/195 中的分拆的没有带日历/历法的翻译

2022-07-18 21:44 UTC, jhdxr requested changes

2022-07-18 21:44 UTC, jhdxr commented on reference/calendar/functions/frenchtojd.xml
> +  <refpurpose>从法国历日期转换为儒略日数</refpurpose>
```suggestion
  <refpurpose>从法国共和历日期转换为儒略日数</refpurpose>
```

参考wiki此处采用全称？https://zh.wikipedia.org/zh-cn/%E6%B3%95%E5%9C%8B%E5%85%B1%E5%92%8C%E6%9B%86

毕竟是首次出现，也不是常用名词/说法。

2022-07-18 21:44 UTC, jhdxr commented on reference/calendar/functions/frenchtojd.xml
> +   This more than covers the period when the calendar was in use.
```suggestion
  这涵盖并且超出了这个历法实际上采用的时间。
```

2022-07-18 21:44 UTC, jhdxr commented on reference/calendar/functions/jdtofrench.xml
> +  <refpurpose>从儒略日数转换为法国历</refpurpose>
```suggestion
  <refpurpose>从儒略日数转换为法国共和历</refpurpose>
```

同上，第一次出现我建议采用完整名称

2022-07-18 21:44 UTC, jhdxr commented on reference/calendar/functions/jewishtojd.xml
> +       assumed.
```suggestion
       如果这个月只有29天，则假定为下个月的第一天。
```

2022-07-18 21:46 UTC, jhdxr commented
辛苦了，我**只**基于PR看了一下内容，具体见上面的review。

后续如果我又消失了很久而有人想帮忙review 的话，欢迎补充下格式的检查（与en版对比tag数是否一致）——感觉又是一个我很久之前想做成GH action但是迟迟没有行动的东西。

2022-07-19 13:34 UTC, mowangjuanzi commented on reference/calendar/functions/jewishtojd.xml
> +       assumed.
我用代码测试了一下。

```php
$b = jewishtojd(2, 30, 5782); // 2459524
$c = jewishtojd(3, 1, 5782); // 2459524
```

翻译成这样你觉得如何：

```text
如果这个月只有 29 天，则假定第 30 天为下个月的第一天。
```

2022-07-20 03:04 UTC, jhdxr commented on reference/calendar/functions/jewishtojd.xml
> +       assumed.
LGTM

2022-07-20 03:06 UTC, jhdxr reviewed
内容上我没啥问题了，所以我先将我的request changes改成comment了，没有直接改成approve的原因是上面说的格式我还没看 o(╯□╰)o

2022-07-20 03:07 UTC, mowangjuanzi commented on reference/calendar/functions/jewishtojd.xml
> +       assumed.
已经更新了

2022-11-01 22:07 UTC, merged