Update implode.xml
php/doc-zh pull request #213
Opened 2022-03-24 09:58 UTC by LIXiangChen

按英文文档进行了修改，主要是：1、参数的名称变了；2、添加了对8.0.0中已移除遗留写法的说明

2022-03-24 10:03 UTC, sy-records requested changes

2022-03-24 10:03 UTC, sy-records commented on reference/strings/functions/implode.xml
>  <!-- EN-Revision: e50c87114588f058084e4cca47b95ddbe4a3bb1c Maintainer: daijie Status: ready -->
commit id 也要对齐英文文档

2022-03-24 10:38 UTC, LIXiangChen commented on reference/strings/functions/implode.xml
>  <!-- EN-Revision: e50c87114588f058084e4cca47b95ddbe4a3bb1c Maintainer: daijie Status: ready -->
commit id 已修改, 第一次弄, 不太了解, 如果还有问题我再改改

2022-03-25 00:14 UTC, sy-records commented
你这个还是不对哈

1. `Maintainer`不用修改，可以添加`<!-- CREDITS: li.xc -->`
2. 修改的内容不对，从`e50c871`到`5dfba3`的修改内容不全，需要和英文文档diff下。

2022-03-25 06:33 UTC, LIXiangChen commented
现在应该与英文文档一致了

2022-03-26 00:39 UTC, sy-records commented on reference/strings/functions/implode.xml
> +       要「implode」的由字符串组成的数组。
引号用中文引号`“”`，但是英文里没有用引号表示

2022-03-26 00:39 UTC, sy-records commented on reference/strings/functions/implode.xml
> +   返回一个字符串：将 <parameter>array</parameter> 的所有元素以字符串形式表现并以相同顺序排列出来，每个元素之间夹着 <parameter>separator</parameter> 字符串。
英文原文里没有加`parameter` 就不用加

2022-03-26 00:40 UTC, sy-records approved these changes

2022-03-26 00:41 UTC, merged