Add: translate socket-accept.xml
php/doc-zh pull request #228
Opened 2022-04-27 07:55 UTC by AtlanticF

2022-05-06 00:54 UTC, sy-records requested changes

2022-05-06 00:54 UTC, sy-records commented on reference/sockets/functions/socket-accept.xml
> +   <function>socket_accept</function> 将直接返回 &false;。
这里的部分需要增加换行，参考[这里](https://github.com/php/doc-zh#%E6%9C%89%E5%85%B3%E5%9C%A8%E7%BF%BB%E8%AF%91%E5%90%8E%E7%9A%84%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84%E7%A9%BA%E6%A0%BC%E4%B8%8E%E6%8D%A2%E8%A1%8C%E7%9A%84%E8%AF%B4%E6%98%8E)

2022-05-06 05:10 UTC, AtlanticF commented on reference/sockets/functions/socket-accept.xml
> +   <function>socket_accept</function> 将直接返回 &false;。
OK，在保证翻译后展示页面准确无误的前提下我会为过长的行增加换行，提高可读性

2022-05-10 03:19 UTC, sy-records approved these changes

2022-05-10 03:19 UTC, merged