update reference/strings/functions/parse-str.xml
php/doc-zh pull request #282
Opened 2022-08-24 13:53 UTC by mowangjuanzi

2022-08-24 22:59 UTC, sy-records requested changes

2022-08-24 22:59 UTC, sy-records commented on reference/strings/functions/parse-str.xml
> +        极度<emphasis>不建议</emphasis>在没有 <parameter>result</parameter> 参数的情况下使用此函数，
间隔的空格需要注意

2022-08-24 23:24 UTC, mowangjuanzi commented on reference/strings/functions/parse-str.xml
> +        极度<emphasis>不建议</emphasis>在没有 <parameter>result</parameter> 参数的情况下使用此函数，
没看出来。麻烦再次说的明显一点点

2022-08-25 00:13 UTC, sy-records approved these changes

2022-08-25 00:13 UTC, sy-records commented on reference/strings/functions/parse-str.xml
> +        极度<emphasis>不建议</emphasis>在没有 <parameter>result</parameter> 参数的情况下使用此函数，
那没事了，看了下以前的 `emphasis`是没空格

2022-08-25 00:14 UTC, sy-records commented on reference/strings/functions/parse-str.xml
> +        极度<emphasis>不建议</emphasis>在没有 <parameter>result</parameter> 参数的情况下使用此函数，
那没事了，看了一下`emphasis`是没空格

2022-08-25 00:14 UTC, merged