update array part 2
php/doc-zh pull request #298
Opened 2022-08-30 06:04 UTC by mowangjuanzi

2022-08-30 06:44 UTC, kang8 commented on reference/array/functions/array-fill.xml
> +       如果 <function>array_fill</function> 的 <parameter>count</parameter> 超出范围现在将会抛出 <classname>ValueError</classname>，之前会引发
多余空格

```suggestion
       如果 <function>array_fill</function> 的 <parameter>count</parameter> 超出范围现在将会抛出 <classname>ValueError</classname>，之前会引发
```

2022-08-31 00:17 UTC, sy-records requested changes

2022-08-31 00:17 UTC, sy-records commented on reference/array/functions/array-fill.xml
> +       开始；自 PHP 8.0.0 起，负数键将会正常递增。（参见 <link linkend="function.array-fill.example.basic">例子</link>）
```suggestion
       如果 <parameter>start_index</parameter> 是负数，在 PHP 8.0.0 
       之前，返回的数组的第一个索引是 <parameter>start_index</parameter>，
       而后面索引则从 0 开始；自 PHP 8.0.0 起，
       负数键将会正常递增。（参见 <link linkend="function.array-fill.example.basic">例子</link>）
```

2022-08-31 00:17 UTC, sy-records commented on reference/array/functions/array-fill.xml
> +       <constant>E_WARNING</constant> 且函数返回 &false;。
```suggestion
       如果 <function>array_fill</function> 的 <parameter>count</parameter>
       超出范围现在将会抛出 <classname>ValueError</classname>，
       之前会引发 <constant>E_WARNING</constant> 且函数返回 &false;。
```

2022-08-31 13:57 UTC, merged