translate EventConfig
php/doc-zh pull request #60
Opened 2021-07-23 03:29 UTC by mowangjuanzi

翻译 EventConfig 相关

2021-07-23 05:48 UTC, sy-records requested changes
有些翻译语句不通顺，标点符号也有问题，以及翻译对标的英文版本也不对。

2021-07-23 06:51 UTC, mowangjuanzi commented
1. 更新相关 version ID
2. 修正标点符号 
3. 修正一些错别字
4. 添加 `eventConfig::setFlags` 翻译

2021-07-25 14:35 UTC, shiny requested changes

2021-07-25 14:35 UTC, shiny commented on reference/event/eventconfig/setflags.xml
> +      参考 <link linkend="eventbase.constants">EventBase 常量</link>.
请使用全角句号

2021-07-25 14:35 UTC, shiny commented on reference/event/eventconfig/setmaxdispatchinterval.xml
> +      <constant>0</constant>, 它适用于每个优先级事件; 如果设置为
请使用全角标点。

2021-07-26 01:54 UTC, mowangjuanzi commented on reference/event/eventconfig/setmaxdispatchinterval.xml
> +      <constant>0</constant>, 它适用于每个优先级事件; 如果设置为
已更新

2021-07-26 01:54 UTC, mowangjuanzi commented on reference/event/eventconfig/setflags.xml
> +      参考 <link linkend="eventbase.constants">EventBase 常量</link>.
已更新

2021-07-26 01:57 UTC, sy-records commented on reference/event/eventconfig/setmaxdispatchinterval.xml
> +      <constant>0</constant>, 它适用于每个优先级事件; 如果设置为
这里还是

```suggestion
      <constant>0</constant>，它适用于每个优先级事件；如果设置为 
```

2021-07-26 02:00 UTC, mowangjuanzi commented on reference/event/eventconfig/setmaxdispatchinterval.xml
> +      <constant>0</constant>, 它适用于每个优先级事件; 如果设置为
vscode 有点手生，忘记了它不是默认保存的了😓

2021-07-26 02:01 UTC, sy-records commented on reference/event/eventconfig/requirefeatures.xml
> +   输入应用程序需要的 event 模块功能。
这里两个翻译都不一样 实际上应该是一样的

翻译也不通顺

2021-07-26 02:24 UTC, mowangjuanzi commented on reference/event/eventconfig/requirefeatures.xml
> +   输入应用程序需要的 event 模块功能。
已更新

2021-07-26 07:25 UTC, merged