更新 install 其他内容
php/doc-zh pull request #96
Opened 2021-10-18 16:14 UTC by mowangjuanzi

2021-10-19 08:03 UTC, shiny commented on install/cloud/azure.xml
> +  <para>Azure 应用服务通过管理 Windwos Web 应用池来托管 web 应用程序，作为在你自己的 Azure 计算虚拟机或者其他服务器的 web 服务器管理的替代品。
`Windwos` ？

2021-10-19 08:53 UTC, jhdxr requested changes

2021-10-19 08:53 UTC, jhdxr commented on install/cloud/azure.xml
> +  <para> 在 Azure 应用服务中 PHP 将会自动启动。 在 Azure 门户，选择你的站点，你可以选择要使用的 PHP 版本。你可能希望选择比默认更加新的版本。
`enable`是启**用**，不是启**动**

2021-10-19 08:53 UTC, jhdxr commented on install/cloud/azure.xml
> +  <para>因此, PHP 和扩展将跟其他 Windows 服务器一样在 Azure 应用服务上运行。
`just as it will **on** other Windows servers.`
因此, PHP 和扩展将跟**在**其他 Windows 服务器一样在 Azure 应用服务上运行

2021-10-19 08:53 UTC, jhdxr commented on install/cloud/azure.xml
> +      <para>你不能使用 IIS 管理器, 服务器管理器或者 RDP。</para>
中文翻译可以考虑换为顿号？

2021-10-19 13:56 UTC, jhdxr requested changes

2021-10-19 13:56 UTC, jhdxr commented on install/cloud/azure.xml
> +  <para>因此, PHP 和扩展将跟**在**其他 Windows 服务器一样在 Azure 应用服务上运行
hmm，你不需要把星号也复制过来，我只是为了在评论里加粗一下以显示出区别。。。

2021-10-20 07:49 UTC, sy-records commented on install/fpm/configuration.xml
> +        默认值: no. 自 PHP 7.0.29, 7.1.17 and 7.2.5 起可用.
```suggestion
        默认值: no。自 PHP 7.0.29、7.1.17 和 7.2.5 起可用。
```

2021-10-20 07:49 UTC, sy-records commented on install/fpm/configuration.xml
> +        如果进程用户或者组跟主进程用户是不同的, 需设置进程可转储标志 (PR_SET_DUMPABLE prctl)。
```suggestion
        如果进程用户或者组跟主进程用户是不同的，需设置进程可转储标志 (PR_SET_DUMPABLE prctl)。 
```

2021-10-20 07:49 UTC, sy-records commented on install/fpm/configuration.xml
> +        自 PHP 7.3.0 起可用.
```suggestion
        默认值: yes。
        自 PHP 7.3.0 起可用。
```

2021-10-20 15:02 UTC, jhdxr commented on install/cloud/azure.xml
> +  <para>因此, PHP 和扩展将跟**在**其他 Windows 服务器一样在 Azure 应用服务上运行
嗯，你的确丢了一个最后的句号→_→ @mowangjuanzi

2021-10-20 15:18 UTC, mowangjuanzi commented on install/cloud/azure.xml
> +  <para>因此, PHP 和扩展将跟**在**其他 Windows 服务器一样在 Azure 应用服务上运行
我对自己都无语了。感觉还是太粗心

2021-10-21 07:59 UTC, merged